- name: 3.2.1 Ensure source routed packets are not accepted (Scored) 1/2 – sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: net.ipv4.conf.all.accept_source_route,     value: 0 }
    - { name: net.ipv4.conf.default.accept_source_route, value: 0 }
    - { name: net.ipv4.route.flush,                      value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.1 Ensure source routed packets are not accepted (Scored) 2/2 – sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "{{ item.name }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  loop:
    - { name: net.ipv4.conf.all.accept_source_route,     value: 0 }
    - { name: net.ipv4.conf.default.accept_source_route, value: 0 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.2 Ensure ICMP redirects are not accepted (Scored) 1/2 – sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: net.ipv4.conf.all.accept_redirects,     value: 0 }
    - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
    - { name: net.ipv4.route.flush,                   value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.2 Ensure ICMP redirects are not accepted (Scored) 2/2 – sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "{{ item.name }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  loop:
    - { name: net.ipv4.conf.all.accept_redirects,     value: 0 }
    - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.3 Ensure secure ICMP redirects are not accepted (Scored) 1/2 – sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: net.ipv4.conf.all.secure_redirects,     value: 0 }
    - { name: net.ipv4.conf.default.secure_redirects, value: 0 }
    - { name: net.ipv4.route.flush,                   value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.3 Ensure secure ICMP redirects are not accepted (Scored) 2/2 – sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "{{ item.name }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  loop:
    - { name: net.ipv4.conf.all.secure_redirects,     value: 0 }
    - { name: net.ipv4.conf.default.secure_redirects, value: 0 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.4 Ensure suspicious packets are logged (Scored) 1/2 – sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: net.ipv4.conf.all.log_martians,     value: 1 }
    - { name: net.ipv4.conf.default.log_martians, value: 1 }
    - { name: net.ipv4.route.flush,               value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.4 Ensure suspicious packets are logged (Scored) 2/2 – sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "{{ item.name }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  loop:
    - { name: net.ipv4.conf.all.log_martians,     value: 1 }
    - { name: net.ipv4.conf.default.log_martians, value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.5 Ensure broadcast ICMP requests are ignored (Scored) 1/2 – sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 }
    - { name: net.ipv4.route.flush,                 value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.5 Ensure broadcast ICMP requests are ignored (Scored) 2/2 – sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "{{ item.name }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  loop:
    - { name: net.ipv4.icmp_echo_ignore_broadcasts, value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.6 Ensure bogus ICMP responses are ignored (Scored) 1/2 – sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: net.ipv4.icmp_ignore_bogus_error_responses, value: 1 }
    - { name: net.ipv4.route.flush,                       value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.6 Ensure bogus ICMP responses are ignored (Scored) 2/2 – sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "{{ item.name }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  loop:
    - { name: net.ipv4.icmp_ignore_bogus_error_responses, value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.7 Ensure Reverse Path Filtering is enabled (Scored) 1/2 – sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: net.ipv4.conf.all.rp_filter,     value: 1 }
    - { name: net.ipv4.conf.default.rp_filter, value: 1 }
    - { name: net.ipv4.route.flush,            value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.7 Ensure Reverse Path Filtering is enabled (Scored) 2/2 – sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "{{ item.name }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  loop:
    - { name: net.ipv4.conf.all.rp_filter,     value: 1 }
    - { name: net.ipv4.conf.default.rp_filter, value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.8 Ensure TCP SYN Cookies is enabled (Scored) 1/2 – sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: net.ipv4.tcp_syncookies, value: 1 }
    - { name: net.ipv4.route.flush,    value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.2.8 Ensure TCP SYN Cookies is enabled (Scored) 2/2 – sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "{{ item.name }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  loop:
    - { name: net.ipv4.tcp_syncookies, value: 1 }
  tags: [ level 1 server, level 1 workstation ]
