- name: 1.7.1.1 Ensure message of the day is configured properly (Scored)
  command: egrep -i '(\\v|\\r|\\m|\\s)' /etc/motd
  register: result
  failed_when: result.rc == 0
  changed_when: False
  tags: [ level 1 server, level 1 workstation ]

- name: 1.7.1.2 Ensure local login warning banner is configured properly (Not Scored) 1/2
  blockinfile:
    path: /etc/issue
    block: "{{ warning_banner }}"
  tags: [ level 1 server, level 1 workstation ]

- name: 1.7.1.2 Ensure local login warning banner is configured properly (Not Scored) 2/2
  command: egrep -i '(\\v|\\r|\\m|\\s)' /etc/issue
  register: result
  failed_when: result.rc == 0
  changed_when: False
  tags: [ level 1 server, level 1 workstation ]

- name: 1.7.1.3 Ensure remote login warning banner is configured properly (Not Scored) 1/2
  blockinfile:
    path: /etc/issue.net
    block: "{{ warning_banner }}"
  tags: [ level 1 server, level 1 workstation ]

- name: 1.7.1.3 Ensure remote login warning banner is configured properly (Not Scored) 2/2
  command: egrep -i '(\\v|\\r|\\m|\\s)' /etc/issue.net
  register: result
  failed_when: result.rc == 0
  changed_when: False
  tags: [ level 1 server, level 1 workstation ]

- name: 1.7.1.4 Ensure permissions on /etc/motd are configured (Not Scored)
  file:
    path: /etc/motd
    owner: root
    group: root
    mode: 0644
  tags: [ level 1 server, level 1 workstation ]

- name: 1.7.1.5 Ensure permissions on /etc/issue are configured (Scored)
  file:
    path: /etc/issue
    owner: root
    group: root
    mode: 0644
  tags: [ level 1 server, level 1 workstation ]

- name: 1.7.1.6 Ensure permissions on /etc/issue.net are configured (Not Scored)
  file:
    path: /etc/issue.net
    owner: root
    group: root
    mode: 0644
  tags: [ level 1 server, level 1 workstation ]

- name: 1.7.2 Ensure GDM login banner is configured (Scored)
  debug:
    msg: "TODO (Gnome only)"
  tags: [ level 1 server, level 1 workstation ]
