- name: 1.2.3 Ensure gpgcheck is globally activated (Scored) 1/3 – /etc/yum.conf
  ini_file:
    path: /etc/yum.conf
    section: main
    option: gpgcheck
    value: 1
    no_extra_spaces: yes
  tags: [ level 1 server, level 1 workstation ]

- name: 1.2.3 Ensure gpgcheck is globally activated (Scored) 2/3 – /etc/yum.d/*
  shell: "egrep '^gpgcheck ?= ?0' --with-filename --line-number /etc/yum.repos.d/*"
  register: result
  failed_when: result.rc > 1
  tags: [ level 1 server, level 1 workstation ]

- name: 1.2.3 Ensure gpgcheck is globally activated (Scored) 3/4 – /etc/yum.d/*
  debug:
    var: result.stdout_lines
  when: result.rc == 0
  tags: [ level 1 server, level 1 workstation ]

- name: 1.2.3 Ensure gpgcheck is globally activated (Scored) 4/4 – /etc/yum.d/*
  fail:
    msg: "Please set gpgcheck=1 on previous files"
  when: result.rc == 0
  tags: [ level 1 server, level 1 workstation ]
