- name: 3.3.1 Ensure IPv6 router advertisements are not accepted (Not Scored) 1/2 – sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: net.ipv6.conf.all.accept_ra,     value: 0 }
    - { name: net.ipv6.conf.default.accept_ra, value: 0 }
    - { name: net.ipv6.route.flush,            value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.3.1 Ensure IPv6 router advertisements are not accepted (Not Scored) – sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "{{ item.name }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  loop:
    - { name: net.ipv6.conf.all.accept_ra,     value: 0 }
    - { name: net.ipv6.conf.default.accept_ra, value: 0 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.3.2 Ensure IPv6 redirects are not accepted (Not Scored) 1/2 – sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: net.ipv6.conf.all.accept_redirects,     value: 0 }
    - { name: net.ipv6.conf.default.accept_redirects, value: 0 }
    - { name: net.ipv6.route.flush,                   value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.3.2 Ensure IPv6 redirects are not accepted (Not Scored) – sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "{{ item.name }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  loop:
    - { name: net.ipv6.conf.all.accept_redirects,     value: 0 }
    - { name: net.ipv6.conf.default.accept_redirects, value: 0 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.3.3 Ensure IPv6 is disabled (Not Scored)
  lineinfile:
    path: /etc/default/grub
    state: present
    regexp: '^GRUB_CMDLINE_LINUX="((?:.* )?)(:?ipv6\.disable=[01])((:? .*)?)"$'
    line: 'GRUB_CMDLINE_LINUX="\1ipv6.disable=1\3"'
    backrefs: yes
  notify: make grub2 config
  tags: [ level 1 server, level 1 workstation ]
