- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored) 1/2
  modprobe:
    name: cramfs
    state: absent
  tags: [ level 1, server, workstation ]

- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored) 2/2
  lineinfile:
    path:   /etc/modprobe.d/CIS.conf
    create: yes
    line:   'install cramfs /bin/true'
    regexp: '^install cramfs'
  tags: [ level 1, server, workstation ]
