- name: 1.3.1 Ensure AIDE is installed (Scored) (install AIDE)
  yum:
    name: aide
    state: present
  register: result
  tags: [ level 1 server, level 1 workstation ]

- name: 1.3.1 Ensure AIDE is installed (Scored) (initialize AIDE)
  shell: "/usr/sbin/aide --init && mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz" # FIXME "aide" should be in $PATH
  when: result is changed
  tags: [ level 1 server, level 1 workstation ]

- name: 1.3.2 Ensure filesystem integrity is regularly checked (Scored)
  cron:
    name:   "Run AIDE check"
    minute: 0
    hour:   5
    job:    "/usr/sbin/aide --check"
  tags: [ level 1 server, level 1 workstation ]
