- name: 1.1.1 Disable unused filesystems 1/2 – modprobe -r
  modprobe:
    name: "{{ item }}"
    state: absent
  loop: "{{ fs_to_disable }}"
  tags: [ level 1 server, level 1 workstation ]


- name: 1.1.1 Disable unused filesystems 2/2 – modprobe.d
  lineinfile:
    path:   /etc/modprobe.d/CIS.conf
    create: yes
    line:   'install {{ item }} /bin/true'
    regexp: '^install {{ item }} '
  loop: "{{ fs_to_disable }}"
  tags: [ level 1 server, level 1 workstation ]
