- import_tasks: 1.1.1_disable_unused_fs.yml

- import_tasks: 1.1_partitioning.yml

- name: 1.1.21 Ensure sticky bit is set on all world-writable directories (Scored)
  shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t"
  tags: [ level 1 server, level 1 workstation ]

- import_tasks: 1.1.22_disable_automounting.yml
