- name: 1.1.2,6,7,11,12,13 Check directory has its own partition (Scored)
  fail:
    msg: 'Separate partition must exist for {{ item }}'
  when:  ansible_mounts|json_query('[?mount==`' + item + '`].mount') == []
  loop: [ /tmp, /var, /var/tmp, /var/log, /var/log/audit, /home ]
  tags: [ level 2 server, level 2 workstation ]

- name: 1.1.3-5 Ensure nodev,nosuid,noexec options set on /tmp partition (Scored)
  mount:
    path: /tmp
    src: "{{ ansible_mounts|json_query('[?mount==`/tmp`].device')|join('') }}"
    fstype: "{{ ansible_mounts|json_query('[?mount==`/tmp`].fstype')|join('') }}"
    opts: 'nodev,nosuid,noexec'
    state: mounted
  tags: [ level 1 server, level 1 workstation ]

- name: 1.1.8-10 Ensure nodev,nosuid,noexec options set on /var/tmp partition (Scored)
  mount:
    path: /var/tmp
    src: "{{ ansible_mounts|json_query('[?mount==`/var/tmp`].device')|join('') }}"
    fstype: "{{ ansible_mounts|json_query('[?mount==`/var/tmp`].fstype')|join('') }}"
    opts: 'nodev,nosuid,noexec'
    state: mounted
  tags: [ level 1 server, level 1 workstation ]

- name: 1.1.14 Ensure nodev options set on /home partition (Scored)
  mount:
    path: /home
    src: "{{ ansible_mounts|json_query('[?mount==`/home`].device')|join('') }}"
    fstype: "{{ ansible_mounts|json_query('[?mount==`/home`].fstype')|join('') }}"
    opts: 'nodev'
    state: mounted
  tags: [ level 1 server, level 1 workstation ]

- name: 1.1.15 Ensure nodev,nosuid,noexec options set on /dev/shm partition (Scored)
  mount:
    path: /dev/shm
    src: tmpfs
    fstype: tmpfs
    opts: 'nodev,nosuid,noexec'
    state: mounted
  tags: [ level 1 server, level 1 workstation ]
