- name: 3.1.1 Ensure IP forwarding is disabled (Scored) 1/2 – sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: net.ipv4.ip_forward,  value: 0 }
    - { name: net.ipv4.route.flush, value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.1.1 Ensure IP forwarding is disabled (Scored) 2/2 – sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: net.ipv4.ip_forward
    value: 0
    no_extra_spaces: yes
  tags: [ level 1 server, level 1 workstation ]

- name: 3.1.2 Ensure packet redirect sending is disabled (Scored) 1/2 – sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: net.ipv4.conf.all.send_redirects,     value: 0 }
    - { name: net.ipv4.conf.default.send_redirects, value: 0 }
    - { name: net.ipv4.route.flush,                 value: 1 }
  tags: [ level 1 server, level 1 workstation ]

- name: 3.1.2 Ensure packet redirect sending is disabled (Scored) 2/2 – sysctl.conf
  ini_file:
    path: /etc/sysctl.conf
    section: null
    option: "{{ item.name }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
  loop:
    - { name: net.ipv4.conf.all.send_redirects,     value: 0 }
    - { name: net.ipv4.conf.default.send_redirects, value: 0 }
  tags: [ level 1 server, level 1 workstation ]
